# Generated by Django 3.1.4 on 2021-01-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210106_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile_user',
        ),
    ]
