# Generated by Django 3.1.4 on 2021-01-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210106_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_user',
            field=models.CharField(max_length=30),
        ),
    ]
